services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: quietvector-api:dev
    container_name: quietvector-api
    env_file:
      - ../.env
    networks:
      - quietnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8090/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: quietvector-web:dev
    container_name: quietvector-web
    networks:
      - quietnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  caddy:
    image: caddy:2-alpine
    container_name: quietvector-caddy
    ports:
      - "127.0.0.1:8443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - quietnet
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:443/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  quietnet:
    driver: bridge
